-- =====================================================================
--  CoughSense Supabase schema + RLS policies
--
--  Run this once against any Supabase project (production or test) so
--  the backend can read/write the `profiles` and `cough_samples` tables.
--
--  How to run:
--    Supabase Dashboard → SQL Editor → paste this file → Run
--    OR
--    psql "$SUPABASE_DB_URL" -f db/migrations.sql
--
--  Why this is needed:
--    The backend talks to Postgres through PostgREST using the anon key
--    plus the user's JWT. Postgres sees the role as `authenticated` and
--    `auth.uid()` returns the logged-in user. RLS policies below restrict
--    every row to its owner.
-- =====================================================================

-- ---------------------------------------------------------------------
-- profiles — display-name lookup keyed by Supabase auth user id
-- ---------------------------------------------------------------------
create table if not exists public.profiles (
    user_id uuid primary key references auth.users(id) on delete cascade,
    name    text,
    updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
    on public.profiles
    for select
    to authenticated
    using (auth.uid() = user_id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
    on public.profiles
    for insert
    to authenticated
    with check (auth.uid() = user_id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
    on public.profiles
    for update
    to authenticated
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

-- ---------------------------------------------------------------------
-- cough_samples — analysis history (only when user gives consent)
-- ---------------------------------------------------------------------
create table if not exists public.cough_samples (
    id                   bigint generated by default as identity primary key,
    user_id              uuid not null references auth.users(id) on delete cascade,
    filename             text not null,
    cough_confidence     numeric(5, 2),
    fever                boolean default false,
    blood                boolean default false,
    chest_pain           boolean default false,
    difficulty_breathing boolean default false,
    result               text,
    score                int,
    consent              boolean default true,
    created_at           timestamptz not null default now()
);

create index if not exists cough_samples_user_id_idx
    on public.cough_samples (user_id, created_at desc);

alter table public.cough_samples enable row level security;

drop policy if exists "cough_samples_select_own" on public.cough_samples;
create policy "cough_samples_select_own"
    on public.cough_samples
    for select
    to authenticated
    using (auth.uid() = user_id);

drop policy if exists "cough_samples_insert_own" on public.cough_samples;
create policy "cough_samples_insert_own"
    on public.cough_samples
    for insert
    to authenticated
    with check (auth.uid() = user_id);

drop policy if exists "cough_samples_delete_own" on public.cough_samples;
create policy "cough_samples_delete_own"
    on public.cough_samples
    for delete
    to authenticated
    using (auth.uid() = user_id);

-- ---------------------------------------------------------------------
-- Storage bucket for uploaded WAV files
-- ---------------------------------------------------------------------
insert into storage.buckets (id, name, public)
    values ('cough-data', 'cough-data', true)
    on conflict (id) do nothing;

drop policy if exists "cough_data_upload_own" on storage.objects;
create policy "cough_data_upload_own"
    on storage.objects
    for insert
    to authenticated
    with check (bucket_id = 'cough-data');

drop policy if exists "cough_data_select_public" on storage.objects;
create policy "cough_data_select_public"
    on storage.objects
    for select
    to public
    using (bucket_id = 'cough-data');
